full_rebuild: true
name: Open Data Tool Kit
author: Code for Aotearoa
version: v1.0
encoding: utf-8
defaults:
  -
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
destination: docs
collections:
- entries
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
